version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/fintrack
    overwrite: true

hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: after_install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user
